server:
  port: 8040
spring:
  datasource:
    url: jdbc:postgresql://185.8.173.130:5432/reservation_db
    driver-class-name: org.postgresql.Driver
    username: reserve_user
    password: Qmars@0109
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  freemarker:
    allow-session-override:
  #----------- config file
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  data:
    redis:
      port: 6379
      host: 185.8.173.130
      jedis:
        pool:
          enabled: true
          min-idle: 10
  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: false
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 20
    leaseExpirationDurationInSeconds: 20
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8010/eureka